from typing import Any, Protocol, runtime_checkable

from guard_core.sync.protocols.redis_protocol import SyncRedisHandlerProtocol


@runtime_checkable
class SyncAgentHandlerProtocol(Protocol):
    def initialize_redis(self, redis_handler: SyncRedisHandlerProtocol) -> None: ...
    def send_event(self, event: Any) -> None: ...
    def send_metric(self, metric: Any) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def flush_buffer(self) -> None: ...
    def get_dynamic_rules(self) -> Any | None: ...
    def health_check(self) -> bool: ...
