from typing import Protocol, runtime_checkable

from guard_core.sync.protocols.agent_protocol import SyncAgentHandlerProtocol
from guard_core.sync.protocols.redis_protocol import SyncRedisHandlerProtocol


@runtime_checkable
class SyncGeoIPHandler(Protocol):
    @property
    def is_initialized(self) -> bool: ...
    def initialize(self) -> None: ...
    def initialize_redis(self, redis_handler: SyncRedisHandlerProtocol) -> None: ...
    def initialize_agent(self, agent_handler: SyncAgentHandlerProtocol) -> None: ...
    def get_country(self, ip: str) -> str | None: ...
    def refresh(self) -> None: ...
    def close(self) -> None: ...
