from typing import Any, Protocol, runtime_checkable

from typing_extensions import ContextManager


@runtime_checkable
class SyncRedisHandlerProtocol(Protocol):
    def get_key(self, namespace: str, key: str) -> Any: ...
    def set_key(
        self, namespace: str, key: str, value: Any, ttl: int | None = None
    ) -> bool | None: ...
    def delete(self, namespace: str, key: str) -> int | None: ...
    def keys(self, pattern: str) -> list[str] | None: ...
    def initialize(self) -> None: ...
    def get_connection(self) -> ContextManager[Any]: ...
